### ISSUE TITLE
Stopping the Rstudio and Jupyter containers from the dashboard should also imply pushing of content to Gitlab

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#107]

**Comment by johanvonboer** [comment]
Just a note which is semi-related to this is that whenever the server is shutdown (assuming it is done in a controlled manner) any running sessions with be auto-committed & pushed to gitlab. But this also assumes that the user has clicked the save button in rstudio/jupyter so that the files have actually changed on (the virtual) drive.

**Comment by johanvonboer** [comment]
Another note regarding this: I had a look at what's available regarding hooking into RStudio save-functionality (to see if we could do an automatic commit & push every time you click save inside RStudio), and there IS a hook/event for "fileSave" that you can tap into, but unfortunately only for the pro/workbench-version.

There also seems to be something similar for Jupyter, but I haven't looked further into that since if we are going to solve it this way it needs to be a consistent behavior across applications so it wouldn't make sense to do it in Jupyter if we can't do it in RStudio.

**Comment by johanvonboer** [comment]
Here's another idea: How about we let the dashboard-part of the system continually check somehow (not sure right now if this needs to be done in intervals or if it can be done via events) if any changes has been done (& saved) in a running rstudio/jupyter container and then create a popup dialog asking the user if they would like to commit & push these changes to gitlab?

So the workflow would look like this: User logs into visp and launches e.g. rstudio, they do some changes and save these within rstudio. Then when they click "back to dashboard" they are immediately greeted by a dialog (on the dashboard page) asking them if they would like to commit & push the changes they just made to gitlab.

I think that might work ok for now as a way to alert users to the fact that just saving inside the container/session is not enough, or what do you think?

**Comment by TomasSkotare** [comment]
Considering the new version does not even use GIT, I think we can close this issue for now.
