### ISSUE TITLE
Cannot log in (404)

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#116]
I cannot log on using my Umu-ID right now. Connected with https://github.com/humlab-speech/visible-speech-deployment/commit/b130c1bfdc97ae1ae301675f665a393d396aa4e3 ? 

I get "404 page not found" after having entered my credentials.

**Comment by johanvonboer** [comment]
Yes it's connected in the way that this is what caused everything to go offline, but not because of the changes I made, it seems to be because traefik, which we use as our edge-router, just suddenly decided to stop working when I tried to restart it. I'm working on replacing traefik with an nginx setup instead, but until then the site is unfortunately down.

**Comment by johanvonboer** [comment]
Finally, it's up again. There were at least 2 issues:
1. I must have accidentally pulled in some changes from github that I shouldn't have since apache was configured wrong for working with traefik.
2. The built-in certbot integration in traefik had stopped working correctly, still not sure why, temporarily removing the auto redirect from http to https fixed it.

**Comment by FredrikKarlssonSpeech** [comment]
The web app is not connecting. Is this a related issue perphaps? 

Reopening the issie.

**Comment by johanvonboer** [comment]
Fixed it
