### ISSUE TITLE
Change the "server connection lost / restored" messages to a latency meter

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#120]

**Comment by johanvonboer** [comment]
I have now (instead) simply removed the "lost connection" and "connection rerestablished" messages, since they are not really indicative of a problem in almost all cases, and in the few cases where there really are serious connection problems, such as the user having lost their internet connection, you will still get a message saying "failed to reconnect to backend".
