### ISSUE TITLE
Sometimes login using an IDP 

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#145]
```
Unknown or Unusable Identity Provider

The identity provider supplying your login credentials is not authorized for use with this service or does not support the necessary capabilities.

To report this problem, please contact the site administrator at [support@humlab.umu.se](mailto:support@humlab.umu.se).

Please include the following error message in any email:

Identity provider lookup failed at (https://visp.humlab.umu.se/Shibboleth.sso/DS/Login)

EntityID: http://adfs.umu.se/adfs/services/trust

opensaml::saml2md::MetadataException: Unable to locate metadata for identity provider (http://adfs.umu.se/adfs/services/trust)
```

**Comment by johanvonboer** [comment]
This is now working again after manually updating the IdP-metadata file, it seems that this expires after some amount of time. In theory this should never be a problem since according to SWAMID's reference configuration the metadata file should be automatically updated by Shibboleth, but if we let Shibboleth try to do this, it won't even startup, which I assume is because the metadata file is too large to download and parse before some sort of timeout kicks in.

Not sure how to solve this at the moment. We could just setup a cron-script to download the metdatafile periodically, but it also needs to be reloaded by Shibboleth, and periodically restarting Apache to achieve this seems like an ugly solution...

**Comment by johanvonboer** [comment]
I have fixed it by increasing the bootup timeout for Shibboleth, the downside is that this means that the system takes 20-30 minutes to start every time you wish to start/restart it.

**Comment by FredrikKarlssonSpeech** [comment]
Ok closed then.
