### ISSUE TITLE
Missing fms and f0 files

### ISSUE THREAD

**Issue by johanvonboer** [humlab-speech/visible-speech-deployment#194]
When a new VISP project is created, a number of R functions are called, including some variant of the add tracks functions, which should generate the fms and f0 files. This works fine when creating a new project with uploaded wav files.

However, when adding files or sessions to an existing project, it does not work. Here's me replicating the operations being performed in RStudio so that I can see the output better:

![image](https://github.com/humlab-speech/visible-speech-deployment/assets/34707290/0543f020-f3ab-4594-8646-7f5c2537874d)

There seems to be some sort of type casting going wrong in the updated Reindeer versions? And if I try to use the older ssff-function it seems that it doesn't want to execute since there already is track files for other wavs in the emudb (which is correct), but I need it to run for the new files...

Hoping @FredrikKarlssonSpeech can have a look at this?

**Comment by FredrikKarlssonSpeech** [comment]
Quick fix @johanvonboer :

Remove the add_trackDedinition calls (and the duplicate application of ksvF0) and replace them with just these `add_ssffTrackDefinition` calls, like so:

```
emuR::add_ssffTrackDefinition(VISPDB, name = "FORMANTS", onTheFlyFunctionName = "forest")
emuR::add_ssffTrackDefinition(VISPDB, name = "F0", onTheFlyFunctionName = "ksvF0")
```

(The last error is caused by the previous call first inserting the track def and name into the DBconfig file, and when computations then fail, there is no cleanup code).

**Comment by johanvonboer** [comment]
That seems to have fixed it, thanks!
