### ISSUE TITLE
The bugs surrounding wav file import and SSFF file generation have resurfaced

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#206]
If you create a new project and import one session, then the contents of this project will be

```
jovyan@4641dc92ca9c:~/project$ find Data/VISP_emuDB/
Data/VISP_emuDB/
Data/VISP_emuDB/VISP_DBconfig.json
Data/VISP_emuDB/VISP_emuDBcache.sqlite
Data/VISP_emuDB/Session 1_ses
Data/VISP_emuDB/Session 1_ses/Session 1.meta_json
Data/VISP_emuDB/bundleLists
Data/VISP_emuDB/bundleLists/all_bundleList.json
Data/VISP_emuDB/bundleLists/frkkan96_at_umu_dot_se_bundleList.json
```

There should be .wav files and fo/formant files in the session, not just the metadata json files.

Have we started using reindeer again at import??

**Comment by TomasSkotare** [comment]
Just for a comment, I do not think we have started using reindeer again; but we could, technically I believe if that is required. I think we solved the previous issues.

**Comment by johanvonboer** [comment]
This was two different (and new) issues that I mistakenly introduced in the new version I uploaded a couple of weeks ago. It was partly that the upload endpoint now did a whitelist check before allowing the upload, but it didn't do it correctly. And partly that the 'more intelligent' version of the addTracks R-code that I committed turned out to be less intelligent in that there was some flawed logic/wrong assumptions made that the dbConfig file should contain track definitions, but actually these definitions are created as the R code for adding the tracks is being run.

Anyway, both of these things are now fixed.
