### ISSUE TITLE
The Emu web app is not connected to the database in gitlab when started? 

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#39]

**Comment by johanvonboer** [comment]
Yes it should be, but when I peaked into your RStudio session I saw that you were using a non-standard directory structure, in which case it won't work. It's an interesting use-case that we should probably discuss how to handle.

**Comment by johanvonboer** [comment]
I should probably mention that the expected path is Data/humlabspeech_emuDB, so if you change it to that I think it should work.

**Comment by FredrikKarlssonSpeech** [comment]
Ok,

I have renamed the emuDB now, and the database works locally. I can serve it from R and connect to it.
However, when I try to connect to it from the web app we serve, I get his error:

`
Error validating bundleList: { "message": "invalid type: object (expected array)", "code": 0, "dataPath": "", "schemaPath": "/type", "subErrors": null, "stack": "ValidationError@https://emuwebapp.speech.humlab.umu.se/dist/emuwebapp.bundle.js:37353:21\nhttps://emuwebapp.speech.humlab.umu.se/dist/emuwebapp.bundle.js:36341:28\nvalidateType@https://emuwebapp.speech.humlab.umu.se/dist/emuwebapp.bundle.js:36724:25\nvalidateBasic@https://emuwebapp.speech.humlab.umu.se/dist/emuwebapp.bundle.js:36694:31\nhttps://emuwebapp.speech.humlab.umu.se/dist/emuwebapp.bundle.js:36575:32\nvalidate@https://emuwebapp.speech.humlab.umu.se/dist/emuwebapp.bundle.js:37453:35\nhttps://emuwebapp.speech.humlab.umu.se/dist/emuwebapp.bundle.js:131960:52\nhttps://emuwebapp.speech.humlab.umu.se/dist/emuwebapp.bundle.js:129967:58\nhttps://emuwebapp.speech.humlab.umu.se/dist/emuwebapp.bundle.js:136367:83\nonInvoke@https://emuwebapp.speech.humlab.umu.se/dist/emuwebapp.bundle.js:5313:39\nhttps://emuwebapp.speech.humlab.umu.se/dist/emuwebapp.bundle.js:107969:49\nhttps://emuwebapp.speech.humlab.umu.se/dist/emuwebapp.bundle.js:108708:37\nonInvokeTask@https://emuwebapp.speech.humlab.umu.se/dist/emuwebapp.bundle.js:5304:43\nhttps://emuwebapp.speech.humlab.umu.se/dist/emuwebapp.bundle.js:108014:57\ndrainMicroTaskQueue@https://emuwebapp.speech.humlab.umu.se/dist/emuwebapp.bundle.js:108420:42\npromiseReactionJob@[native code]" }
`

**Comment by johanvonboer** [comment]
I had a look in your project and the problem is that you don't have any bundlelist. This is auto-generated if the emudb is created along with the project, which is the intention... but perhaps we should support this use-case as well where a more advanced user might wish to create an empty project and then manually create their own emudb. There's a few problems that we have to tackle if we go that route, such as:

1. When launching the project in the emuwebapp, we need to know the name of the emudb directory.
2. We need to somehow detect if the project contains an emudb or not, and not show the emuwebapp button if it doesn't.

**Comment by johanvonboer** [comment]
I discovered that we were affected by https://github.com/IPS-LMU/emuR/issues/248

Switched to using dev version of emuR

Fix is not deployed in production yet
