### ISSUE TITLE
Long loading times for large projects

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#52]
You need to reload the page for the label to update (Safari browser)

**Comment by johanvonboer** [comment]
Cannot replicate (unfortunately) using Safari 12.1

Steps:
1. Go to speech.humlab.umu.se
2. Click on Jupyter button
3. Wait until Jupyter loads and we are redirected to it
4. Click browser back button twice to come back to portal site - status now shows "Running"

Are these steps in any way different to what you were doing? @liasam92 @FredrikKarlssonSpeech

**Comment by FredrikKarlssonSpeech** [comment]
I have a movie :-).

The issue is that the progress bar never finishes, so you learn that jypyter has started only when you reload the page.



https://user-images.githubusercontent.com/200246/117978188-e6b01180-b331-11eb-92b8-acd325a6eb77.mov

**Comment by johanvonboer** [comment]
Thanks! Now I'm thinking it has to do with the very long load time you have on this project. Have you tried waiting for a very long time, like 10 minutes or so? - Just as an experiment. I'm thinking it could be that when you hit refresh at the end of the this movie (I assume that's what happening) it's actually still in the process of cloning out the project from gitlab. You could enter jupyter at this point and everything will seem normal, I suppose, but the project would be still be in the process of being downloaded and it could complete after 2 seconds or 10 minutes, who knows, that's why the user is not being redirected into the container before the cloning is done, even though the container is technically ready much sooner.

Also, these long loading times are of course a problem in their own right, but that's a bigger discussion...
