### ISSUE TITLE
Rstudio /Jypyter "Save" should perhaps mean "sync"?

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#76]
If you start an Rstudio session, go to the Web app, do some transcriptions, and then go back to Rstudio again, somehow we need to be able to make the new data available to the Rstudio / Jypyter sessions.

in this day of everything being "Synced" everywhere, maybe the user would understand "Sync" as an alternative to "Save", but bidirectional?

**Comment by johanvonboer** [comment]
There's a problem with conflicts if changes were made in both rstudio and emu webapp. A 'solution' is to only let the user have one application launched at any one time, this would work fine in the case of having rstudio or jupyter running then we could just block access to emu webapp, but it's more of an unknown to me right now how/if we could block the user from launching rstudio while being inside emu-webapp (in another tab) since that's not a container/session in the same way.

Will have to look into that if we decide that is a good way forward.

**Comment by FredrikKarlssonSpeech** [comment]
If we make #83 happen, then we will have sorted this one too.

**Comment by johanvonboer** [comment]
The issue with emu-webapp remains - meaning that the user can launch emu-webapp, and then go to the visp-domain in another tab and launch something else there, since I can't detect if the user is currently in a emu-webapp session or not. But I think it's an issue we can live with for now, since this is only about protecting the user from themselves, so if they insist on going out of their way to shoot themselves in the foot by doing it this way... then I guess we can let them?

**Comment by johanvonboer** [comment]
Realized now this issue was already closed - good! :)
