### ISSUE TITLE
Voice Analys Toolbox as an internal Matlab web service 

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#90]
Voice Analysis Toolbox URLs
https://www.darth-group.com/software
https://www.dropbox.com/s/5iy11htw3arv0py/VoiceAnalysisToolbox.zip?dl=0

**Comment by TomasSkotare** [comment]
As of commit 1a5b3027fd8ddff25dc0542f42f165e960f946f6 , this has been included instead as a Matlab runtime compiled program in the jupyter notebook, and can be run from there by each user. This should be used instead of a web service to ensure that no information can leak between users.

I recommend that we should test the current solution, and then create new scripts (both R and Python) for easier access to the commands.
